Repository pouladpld/Tank-Mania, pull requests merged in 2018-03, with the labels that each got.

#14 Fix #8 Prevent mirroring tank health bar
  Assets/Prefabs/Tank.prefab
  Assets/Scripts/Tank/TankBehavior.cs
  Assets/Scripts/Tank/TankBehavior2.cs
  ProjectSettings/ProjectVersion.txt
Labels: bug

#18 Issue17 - Menu GUI
  Assets/Editor/WebGLBuilder.cs
  Assets/Fonts.meta
  Assets/Fonts/terminatortwo.ttf
  Assets/Fonts/terminatortwo.ttf.meta
  Assets/Scenes/Menu.unity
  Assets/Scenes/Menu.unity.meta
  Assets/Scripts/Menu.meta
  Assets/Scripts/Menu/MenuHandler.cs
  Assets/Scripts/Menu/MenuHandler.cs.meta
  Assets/Sprites/keyboard_key_a.png
  Assets/Sprites/keyboard_key_a.png.meta
  Assets/Sprites/keyboard_key_d.png
  Assets/Sprites/keyboard_key_d.png.meta
  Assets/Sprites/keyboard_key_e.png
  Assets/Sprites/keyboard_key_e.png.meta
  Assets/Sprites/keyboard_key_esc.png
  Assets/Sprites/keyboard_key_esc.png.meta
  Assets/Sprites/keyboard_key_q.png
  Assets/Sprites/keyboard_key_q.png.meta
  Assets/Sprites/tank_bg.jpg
  Assets/Sprites/tank_bg.jpg.meta
  Assets/Sprites/weapons.png
  Assets/Sprites/weapons.png.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: feature, priority:high

#21 Turn timeout + Current player name
  Assets/Scenes/Playground.unity
  Assets/Scripts/Scene Management/SceneManagerBehavior.cs
  Assets/Scripts/Scene Management/SceneManagerBehavior2.cs
  Assets/Scripts/Tank/TankBehavior.cs
Labels: feature, priority:high

#26 Rotations
  Assets/Scripts/Tank/TankBehavior2.cs
Labels: priority:high
